## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.4
  - 1.5
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

before_install:
  - julia --project -e 'import Pkg; Pkg.add(PackageSpec(url="https://github.com/ahumenberger/Recurrences.jl"));'
  - julia --project -e 'import Pkg; Pkg.add(PackageSpec(url="https://github.com/ahumenberger/AlgebraicDependencies.jl"));'
